name: Solar System Workflow

on:
    workflow_dispatch:
    push:
        branches:
            - 'main'
            - 'feature/*'
        paths:
            - '**.js'

jobs:
    unit-testing: 
        name: Unit Testing
        runs-on: ubuntu:latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            - name: Install node.js
              uses: actions/setup-node@v4.0.2
              with:
                node-version: 18
            - name: Install dependencies
              run: npm install
            - name: Run unit tests
              run: npm test